CREATE TABLE Customers (
    id INTEGER  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    surname VARCHAR NOT NULL,
    patronymic VARCHAR,
    phone varchar(10) NOT NULL
);

CREATE TABLE Suppliers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL
);

CREATE TABLE Manufacturer (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL
);

CREATE TABLE Medicines (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    manufacturer_id integer references Manufacturer(id),
    dosage varchar NOT NULL
);

CREATE TABLE Orders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id INTEGER REFERENCES Customers(id) ON DELETE CASCADE,
    order_date DATE NOT NULL,
    delivery_date DATE,
    delivery_address VARCHAR NOT NULL
);

CREATE TABLE Storages (
    id integer primary key generated by default as identity,
    name varchar not null,
    phone varchar not null,
    address varchar not null
);

CREATE TABLE Supply (
    id integer primary key generated by default as identity,
    supplier_id integer references Suppliers(id),
    supply_date date not null,
    storage_id integer references Storages(id)
);

CREATE TABLE SupplyList (
    id integer primary key generated by default as identity,
    medicine_id integer references Medicines(id),
    supply_id integer references Supply(id),
    amount integer,
    cost_per_piece integer
);

CREATE TABLE OrderList (
    order_id integer references Orders(id) ON DELETE CASCADE,
    supply_list_id integer references SupplyList(id),
    medicine_id integer references Medicines(id),
    amount integer
);


-- customers, suppliers, manufacturer, medicines, orders
-- storages, supply, supplylist, orderlist


